//
//  AppHeaderView.swift
//  Steganographer
//
//  Created by Łukasz Stachnik on 14/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import UIKit
import IteoLogger

final class AppHeaderView: XibView {

    var backAction = SimpleAction()

    @IBOutlet weak var backButton: UIImageView!
    @IBOutlet weak var headerTitle: UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
    }

    func setup(title: String, isBack: Bool, action: @escaping SimpleAction) {
        backButton.isHidden = isBack
        backAction = action
        headerTitle.text = title
    }

    func setup(title: NSAttributedString, isBack: Bool, action: @escaping SimpleAction) {
        backButton.isHidden = isBack
        backAction = action
        headerTitle.attributedText = title
    }
}

private extension AppHeaderView {
    
    private func setupGestures() {
        let tap = UITapGestureRecognizer(target: self, action: <#T##Selector?#>)
        backButton.addGestureRecognizer()
        
    }

    @objc func backTap() {
        backAction()
    }
}
