//
//  AppHeaderView.swift
//  Steganographer
//
//  Created by Łukasz Stachnik on 14/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import UIKit
import IteoLogger

final class AppHeaderView: XibView {

    @IBOutlet var backButton: UIButton!
    @IBOutlet private var headerTitle: UILabel!

    private weak var controller: UIViewController?

    func setup(in controller: UIViewController?,
               title: String,
               ignoreBackButton: Bool = false) {
        backButton.isHidden = ignoreBackButton
        headerTitle.text = title
        configureNavigationBackButton(in: controller)
    }

    func setup(in controller: UIViewController?,
               title: NSAttributedString,
               ignoreBackButton: Bool = false) {
        backButton.isHidden = ignoreBackButton
        headerTitle.attributedText = title
        configureNavigationBackButton(in: controller)
    }
}

private extension AppHeaderView {
    
    private func configureDefault() {
        setup(in: nil, title: "View Title")
    }

    private func configureNavigationBackButton(in controller: UIViewController?) {
        self.controller = controller
        configureBackButton()
    }

    private func configureBackButton() {
        backButton.addTarget(self, action: #selector(backTap), for: .touchUpInside)
    }
    
    @objc func backTap() {
        assert(controller?.navigationController != nil, "Back tapped, but not in navigation stack")
        controller?.navigationController?.popViewController(animated: true)
    }
}
