//
//  AppHeaderView.swift
//  Steganographer
//
//  Created by Łukasz Stachnik on 14/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import UIKit
import IteoLogger

final class AppHeaderView: XibView {

    var backAction: SimpleAction?

    @IBOutlet private var backButton: UIImageView!
    @IBOutlet private var headerTitle: UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
        setupGestures()
    }

    func setup(title: String, isBack: Bool) {
        backButton.isHidden = !isBack
        headerTitle.text = title
    }

    func setup(title: NSAttributedString, isBack: Bool) {
        backButton.isHidden = !isBack
        headerTitle.attributedText = title
    }
}

private extension AppHeaderView {

    private func setupGestures() {
        let tap = UITapGestureRecognizer(target: self, action: #selector(backTap))
        backButton.addGestureRecognizer(tap)
    }

    @objc func backTap() {
        backAction?()
    }
}
