//
//  HomeCardViewView.swift
//  Steganographer
//
//  Created by Łukasz Stachnik on 11/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import UIKit
import IteoLogger

final class HomeCardViewView: XibView {

    @IBOutlet private var nameLabel: UILabel!
    @IBOutlet private var backgroundImage: UIImageView!
    private var type: CardViewType = .encoding

    var tapAction: SimpleAction?

    override func awakeFromNib() {
        super.awakeFromNib()
        setupView()
    }

    func setup(with type: CardViewType) {
        nameLabel.text = type.title
        backgroundImage.image = type.image
        setupView()
    }
}

private extension HomeCardViewView {

    private func setupView() {
        setupTapGesture()
        backgroundImage.layer.cornerRadius = 15
    }

    private func setupTapGesture() {
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(tapGestureAction))
        addGestureRecognizer(tapGesture)
    }

    @objc private func tapGestureAction() {
        tapAction?()
    }
}
